"""empty message

Revision ID: 4361996acb26
Revises: 54a690f2c225
Create Date: 2023-02-03 18:21:43.675090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4361996acb26'
down_revision = '54a690f2c225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'carrito', 'user', ['id_usuario'], ['id'])
    op.drop_constraint('favoritos_id_usuario_key', 'favoritos', type_='unique')
    op.create_foreign_key(None, 'favoritos', 'user', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'metodos_de_pagos', 'user', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metodos_de_pagos', type_='foreignkey')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.create_unique_constraint('favoritos_id_usuario_key', 'favoritos', ['id_usuario'])
    op.drop_constraint(None, 'carrito', type_='foreignkey')
    # ### end Alembic commands ###
