"""empty message

Revision ID: 77140a87e388
Revises: f47ff0fa0131
Create Date: 2023-02-25 17:15:45.423669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77140a87e388'
down_revision = 'f47ff0fa0131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagenes', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_column('imagenes')

    # ### end Alembic commands ###
