"""empty message

Revision ID: 90e86dcd95a0
Revises: 77140a87e388
Create Date: 2023-02-25 17:17:15.977323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e86dcd95a0'
down_revision = '77140a87e388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=10000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
