"""empty message

Revision ID: 99c9664e3d8c
Revises: 
Create Date: 2023-02-13 17:11:39.598005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c9664e3d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('productype', sa.String(length=120), nullable=False),
    sa.Column('product_url', sa.String(length=240), nullable=False),
    sa.Column('keywords', sa.String(length=240), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('sell_on_amazon', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('main_image', sa.String(length=500), nullable=False),
    sa.Column('color', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('dimensions', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('direccion_de_entrega', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('celular', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producto_sku', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['producto_sku'], ['producto.sku'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producto_sku', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['producto_sku'], ['producto.sku'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodos_de_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metodos_de_pagos')
    op.drop_table('favoritos')
    op.drop_table('carrito')
    op.drop_table('user')
    op.drop_table('producto')
    # ### end Alembic commands ###
