"""empty message

Revision ID: 9bf6d80cd587
Revises: e446f7ff9047
Create Date: 2023-02-26 23:59:23.151722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf6d80cd587'
down_revision = 'e446f7ff9047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_sku', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imagenes', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=12000), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200000), nullable=True))
        batch_op.drop_constraint('favoritos_producto_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['producto_sku'], ['sku'])
        batch_op.drop_column('producto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_producto_id_fkey', 'producto', ['producto_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('name')
        batch_op.drop_column('imagenes')
        batch_op.drop_column('producto_sku')

    # ### end Alembic commands ###
