"""empty message

Revision ID: ba8956a23a9f
Revises: c6ea37aa3af7
Create Date: 2023-02-03 17:05:13.418506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8956a23a9f'
down_revision = 'c6ea37aa3af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('metodos_de_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metodos_de_pagos')
    op.drop_table('favoritos')
    # ### end Alembic commands ###
