"""empty message

Revision ID: c25f9d9ca23f
Revises: 9d6659717e02
Create Date: 2023-02-10 20:00:51.259993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25f9d9ca23f'
down_revision = '9d6659717e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('productype', sa.String(length=120), nullable=False),
    sa.Column('product_url', sa.String(length=240), nullable=False),
    sa.Column('keywords', sa.String(length=240), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('sell_on_amazon', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('main_image', sa.String(length=500), nullable=False),
    sa.Column('color', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('dimensions', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('sku'),
    sa.UniqueConstraint('product_url')
    )
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku_product', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('carrito_sku_key', type_='unique')
        batch_op.create_foreign_key(None, 'producto', ['sku_product'], ['sku'])
        batch_op.drop_column('sku')

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_sku_key', type_='unique')
        batch_op.create_foreign_key(None, 'producto', ['sku'], ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('favoritos_sku_key', ['sku'])

    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('carrito_sku_key', ['sku'])
        batch_op.drop_column('sku_product')

    op.drop_table('producto')
    # ### end Alembic commands ###
