"""empty message

Revision ID: c6ea37aa3af7
Revises: e6eb4328b268
Create Date: 2023-02-03 15:09:36.040660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ea37aa3af7'
down_revision = 'e6eb4328b268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('direccion_de_entrega', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('apellido', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('celular', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['celular'])
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['apellido'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'celular')
    op.drop_column('user', 'apellido')
    op.drop_column('user', 'name')
    op.drop_column('user', 'direccion_de_entrega')
    # ### end Alembic commands ###
