"""empty message

Revision ID: f47ff0fa0131
Revises: 3bb95cb3f9c5
Create Date: 2023-02-23 19:22:07.984717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47ff0fa0131'
down_revision = '3bb95cb3f9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=12000), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=12000), nullable=False))
        batch_op.add_column(sa.Column('imagenes', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_column('cantidad')
        batch_op.drop_column('imagenes')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
